### ISSUE TITLE
AtDigester consumes first line of responses as echos

### ISSUE THREAD

**Issue by nbarrios** [atlas-aero/rt-esp-at-nal#13]
I started working on [adding UART config commands](https://github.com/nbarrios/rt-esp-at-nal/commit/34056967b75401788cfc7808990e8cece13a576e) (get/set `AT+UART_CUR` and `AT+UART_DEF`), but the responses always failed to parse.

example response (with echo): `AT+UART_CUR?\r\n+UART_CUR:115201,8,1,0,1\r\n`

 I think I tracked it down to:

```
impl<P: Parser> Digester for AtDigester<P> {
    fn digest<'a>(&mut self, input: &'a [u8]) -> (DigestResult<'a>, usize) {
        // 1. Optionally discard echo
        let (buf, echo_bytes) = match nom::combinator::opt(parser::echo)(input) {
            Ok((buf, echo)) => (buf, echo.unwrap_or_default().len()),
            Err(nom::Err::Incomplete(_)) => return (DigestResult::None, 0),
            Err(_) => panic!("NOM ERROR - opt(echo)"),
        };

        // 2. Match for URC's
        if let Ok((urc, len)) = P::parse(input) {
            return (DigestResult::Urc(urc), len);
        }

        // 3. Parse for success responses
        // Custom successful replies first, if any
        if let Ok((response, len)) = (self.custom_success)(buf) {
            return (DigestResult::Response(Ok(response)), len + echo_bytes);
        }
...
```
That first step always seems to discard the first line as an echo, but then the original input is used to match for URCs. URCDigester then [matches](https://github.com/pegasus-aero/rt-esp-at-nal/blob/465437ca39a0f26db1983e8c8f9d7149a6f4fb69/src/urc.rs#L223) the echo as a valid URC and returns. On the next digest, the first step discards the entire first line of any response (the entire response in the case of `AT+UART_CUR?`).

Preventing URCDigester from matching echos allows the responses to parse correctly. The AtDigester docs suggest that it should work with echo disabled, but it always seems to discard the first line as echo unless I'm misunderstanding something. Another solution is to change AtDigester to hand `P::parse()` the buf after discarding the echo instead of `input` like it does now.

The same issue happens with `get_address()`. The first response disappears (the ipv4 address for me).

I'm new to rust and embedded rust so I appreciate any help.

**Comment by MathiasKoch** [comment]
Hmm, not really sure how to do that, but it will most likely require a custom implementation instead of the derived `AtatCmd`

**Comment by marius-meissner** [comment]
From my point of view #14 fixed the issue. If anyone encounters further errors, please create a new issue.
